### ISSUE TITLE
sector numbers

### ISSUE THREAD

**Issue by dial-888** [jamersonpro/ntfsmarkbad#1]
I know LBA numbers, which I want to mark bad. How can I get physical sector numbers?

**Comment by Engraulis** [comment]
I think they are equal. Don't forget to MarkBad some space before and after bad sector.

**Comment by dial-888** [comment]
> I think they are equal.

After some reading - I assume they are mostly NOT equal. Most HDD nowadays have a 4096 bytes physical sector size, while the default logical sector size is 512 bytes.

**Comment by dial-888** [comment]
After attempt to use this program using physical sector numbers, I come to conclusion that wiki page is misleading me with "Use physical sector numbers of the disk storage, not logical volume sector numbers". I need to do opposite thing - since number of selected clusters is divided by 8 from entered interval, and last sector number is clearly is LBA number of disk sectors.
Anyway I hoped that this program will work fast, but it's slow as any other.

**Comment by Engraulis** [comment]
I manage to disable half-dead head on my HDD using this program - so it's working. The program is buggy but I steel manage to do it. It took 2 week's of my time, but now job is done. Now I'm looking for cluster based program to show read speed in graphic. 

> Anyway I hoped that this program will work fast, but it's slow as any other.

What other programs do you know?

**Comment by joaopaulo1511** [comment]
> Now I'm looking for cluster based program to show read speed in graphic.

[DiskGenius](https://www.diskgenius.com/).  It can boot from an external or even internal storage with a special recovery environment so it can scan the Windows partition.

**Comment by jamersonpro** [comment]
> I know LBA numbers, which I want to mark bad. How can I get physical sector numbers?

Usually they are the same.
But for devices with native 4K sectors, this may not be correct.
The best way is to just run the program and look at the detected range of sectors. In version 0.0.2 an info mode was added for this purpose.
