### ISSUE TITLE
Cannot lock the drive. The volume is still in use.

### ISSUE THREAD

**Issue by Engraulis** [jamersonpro/ntfsmarkbad#2]
[Pazmechalka+log.zip](https://github.com/jamersonpro/ntfsmarkbad/files/6718186/Pazmechalka%2Blog.zip)

See Paz_Log.txt

To disable dead head on my HDD I use Paz.bat and PazPlus.bat - they contain multiple call's of MarkBad like:
```
NtfsMarkBad32.exe t: 40077568 40323840
NtfsMarkBad32.exe t: 40560128 40811392
NtfsMarkBad32.exe t: 41050880 41301248
...
```

But execution of NtfsMarkBad32.exe in batch often gives a error:
```
Cannot lock the drive. The volume is still in use.
An error has occurred.
```
And half of bads does not add to $BasCluster list.

I manage to complete my task using Pz_multi.bat
Just calling Paz.bat again and again until job done.

PS: My HDD is LBA cached by FancyCache
PPS: А па рюски тута спикаютъ?

**Comment by raszpl** [comment]
How did you determine sector map for the bad head?

**Comment by Engraulis** [comment]
HDeadDecaper
https://github.com/Engraulis/HDeadDecaper

**Comment by jamersonpro** [comment]
> 

It looks like some other program is reading the contents of the disk after making changes to the file system.
A pause is probably needed before the next launch of NtfsMarkBad.

In version 0.0.2, a batch mode was added, when many clusters can be marked in one run. Just specify a file with a list of sectors ranges in the parameter, in this format:
```
40077568 40323840
40560128 40811392
41050880 41301248
```
