### ISSUE TITLE
Permanent or semi-permanent fix?

### ISSUE THREAD

**Issue by oywino** [jamersonpro/ntfsmarkbad#3]
Using this program was easy, and it works well under Windows.
But as soon as I plug the disk back into my NAS, the NAS will automatically delete all existing partitions and reformat the drive using EXT4 and create several new partitions under Linux. 
I assume then that the work done by NTFSMARKBAD is lost, and i am back to square one?

**Comment by raszpl** [comment]
You would have to mark bad blocks in drive firmware (G-list/P-list), much lower level and mostly requires paid tools. Example http://www.hddoracle.com/viewtopic.php?f=117&t=1423&p=7345#p7345

**Comment by jamersonpro** [comment]
> Using this program was easy, and it works well under Windows. But as soon as I plug the disk back into my NAS, the NAS will automatically delete all existing partitions and reformat the drive using EXT4 and create several new partitions under Linux. I assume then that the work done by NTFSMARKBAD is lost, and i am back to square one?

Yes.
NtfsMarkBad simply adds entries to the list of bad sectors in the file system.
In the same way as it is done when formatting or after checking with chkdsk.
During re-formatting, this list is cleared.
